// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.11.4
// source: cqlcrude/cqlcrudepb/cqlcrude_messages.proto

package cqlcrude

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// the model of the data to be stored into cassandra
// iccid ascii PRIMARY KEY,
// event_origin ascii, event_type ascii, imsi ascii, msisdn ascii, new_imei
// ascii,
//    notify_status ascii, old_imei ascii, operator_name ascii,
//    sequence_num ascii, service_engine ascii, tac_id ascii,
//    terminal_profile ascii, tracking_status ascii,
//   tracking_time timestamp
type TrackingEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Iccid           string `protobuf:"bytes,1,opt,name=iccid,proto3" json:"iccid,omitempty"`
	EventOrigin     string `protobuf:"bytes,2,opt,name=event_origin,json=eventOrigin,proto3" json:"event_origin,omitempty"`
	EventType       string `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Imsi            string `protobuf:"bytes,4,opt,name=imsi,proto3" json:"imsi,omitempty"`
	Msisdn          string `protobuf:"bytes,5,opt,name=msisdn,proto3" json:"msisdn,omitempty"`
	NewImei         string `protobuf:"bytes,6,opt,name=new_imei,json=newImei,proto3" json:"new_imei,omitempty"`
	NotifyStatus    string `protobuf:"bytes,7,opt,name=notify_status,json=notifyStatus,proto3" json:"notify_status,omitempty"`
	OldImei         string `protobuf:"bytes,8,opt,name=old_imei,json=oldImei,proto3" json:"old_imei,omitempty"`
	OperatorName    string `protobuf:"bytes,9,opt,name=operator_name,json=operatorName,proto3" json:"operator_name,omitempty"`
	SequenceNum     string `protobuf:"bytes,10,opt,name=sequence_num,json=sequenceNum,proto3" json:"sequence_num,omitempty"`
	ServiceEngine   string `protobuf:"bytes,11,opt,name=service_engine,json=serviceEngine,proto3" json:"service_engine,omitempty"`
	TacId           string `protobuf:"bytes,12,opt,name=tac_id,json=tacId,proto3" json:"tac_id,omitempty"`
	TerminalProfile string `protobuf:"bytes,13,opt,name=terminal_profile,json=terminalProfile,proto3" json:"terminal_profile,omitempty"`
	TrackingStatus  string `protobuf:"bytes,14,opt,name=tracking_status,json=trackingStatus,proto3" json:"tracking_status,omitempty"`
	TrackingTime    int64  `protobuf:"varint,15,opt,name=tracking_time,json=trackingTime,proto3" json:"tracking_time,omitempty"`
}

func (x *TrackingEvent) Reset() {
	*x = TrackingEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackingEvent) ProtoMessage() {}

func (x *TrackingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackingEvent.ProtoReflect.Descriptor instead.
func (*TrackingEvent) Descriptor() ([]byte, []int) {
	return file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_rawDescGZIP(), []int{0}
}

func (x *TrackingEvent) GetIccid() string {
	if x != nil {
		return x.Iccid
	}
	return ""
}

func (x *TrackingEvent) GetEventOrigin() string {
	if x != nil {
		return x.EventOrigin
	}
	return ""
}

func (x *TrackingEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TrackingEvent) GetImsi() string {
	if x != nil {
		return x.Imsi
	}
	return ""
}

func (x *TrackingEvent) GetMsisdn() string {
	if x != nil {
		return x.Msisdn
	}
	return ""
}

func (x *TrackingEvent) GetNewImei() string {
	if x != nil {
		return x.NewImei
	}
	return ""
}

func (x *TrackingEvent) GetNotifyStatus() string {
	if x != nil {
		return x.NotifyStatus
	}
	return ""
}

func (x *TrackingEvent) GetOldImei() string {
	if x != nil {
		return x.OldImei
	}
	return ""
}

func (x *TrackingEvent) GetOperatorName() string {
	if x != nil {
		return x.OperatorName
	}
	return ""
}

func (x *TrackingEvent) GetSequenceNum() string {
	if x != nil {
		return x.SequenceNum
	}
	return ""
}

func (x *TrackingEvent) GetServiceEngine() string {
	if x != nil {
		return x.ServiceEngine
	}
	return ""
}

func (x *TrackingEvent) GetTacId() string {
	if x != nil {
		return x.TacId
	}
	return ""
}

func (x *TrackingEvent) GetTerminalProfile() string {
	if x != nil {
		return x.TerminalProfile
	}
	return ""
}

func (x *TrackingEvent) GetTrackingStatus() string {
	if x != nil {
		return x.TrackingStatus
	}
	return ""
}

func (x *TrackingEvent) GetTrackingTime() int64 {
	if x != nil {
		return x.TrackingTime
	}
	return 0
}

type DeleteTrackingEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Iccid string `protobuf:"bytes,1,opt,name=iccid,proto3" json:"iccid,omitempty"`
}

func (x *DeleteTrackingEventRequest) Reset() {
	*x = DeleteTrackingEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTrackingEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTrackingEventRequest) ProtoMessage() {}

func (x *DeleteTrackingEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTrackingEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteTrackingEventRequest) Descriptor() ([]byte, []int) {
	return file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteTrackingEventRequest) GetIccid() string {
	if x != nil {
		return x.Iccid
	}
	return ""
}

// message for delete tracking response
type DeleteTrackingEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Iccid           string `protobuf:"bytes,1,opt,name=iccid,proto3" json:"iccid,omitempty"`
	OperationStatus int32  `protobuf:"varint,2,opt,name=operation_status,json=operationStatus,proto3" json:"operation_status,omitempty"`
}

func (x *DeleteTrackingEventResponse) Reset() {
	*x = DeleteTrackingEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTrackingEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTrackingEventResponse) ProtoMessage() {}

func (x *DeleteTrackingEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTrackingEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteTrackingEventResponse) Descriptor() ([]byte, []int) {
	return file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteTrackingEventResponse) GetIccid() string {
	if x != nil {
		return x.Iccid
	}
	return ""
}

func (x *DeleteTrackingEventResponse) GetOperationStatus() int32 {
	if x != nil {
		return x.OperationStatus
	}
	return 0
}

type SubmitTrackingEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackingEvent *TrackingEvent `protobuf:"bytes,1,opt,name=tracking_event,json=trackingEvent,proto3" json:"tracking_event,omitempty"`
}

func (x *SubmitTrackingEventRequest) Reset() {
	*x = SubmitTrackingEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitTrackingEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTrackingEventRequest) ProtoMessage() {}

func (x *SubmitTrackingEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTrackingEventRequest.ProtoReflect.Descriptor instead.
func (*SubmitTrackingEventRequest) Descriptor() ([]byte, []int) {
	return file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitTrackingEventRequest) GetTrackingEvent() *TrackingEvent {
	if x != nil {
		return x.TrackingEvent
	}
	return nil
}

type ListTrackingEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListTrackingEventRequest) Reset() {
	*x = ListTrackingEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTrackingEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrackingEventRequest) ProtoMessage() {}

func (x *ListTrackingEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrackingEventRequest.ProtoReflect.Descriptor instead.
func (*ListTrackingEventRequest) Descriptor() ([]byte, []int) {
	return file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_rawDescGZIP(), []int{4}
}

type ListTrackingEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackingEvent *TrackingEvent `protobuf:"bytes,1,opt,name=tracking_event,json=trackingEvent,proto3" json:"tracking_event,omitempty"`
}

func (x *ListTrackingEventResponse) Reset() {
	*x = ListTrackingEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTrackingEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrackingEventResponse) ProtoMessage() {}

func (x *ListTrackingEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrackingEventResponse.ProtoReflect.Descriptor instead.
func (*ListTrackingEventResponse) Descriptor() ([]byte, []int) {
	return file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_rawDescGZIP(), []int{5}
}

func (x *ListTrackingEventResponse) GetTrackingEvent() *TrackingEvent {
	if x != nil {
		return x.TrackingEvent
	}
	return nil
}

// the response after submitting tracking event,0 is OK otherwise it is bad
type SubmitTrackingEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubmitStatus int32 `protobuf:"varint,1,opt,name=submit_status,json=submitStatus,proto3" json:"submit_status,omitempty"`
}

func (x *SubmitTrackingEventResponse) Reset() {
	*x = SubmitTrackingEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitTrackingEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTrackingEventResponse) ProtoMessage() {}

func (x *SubmitTrackingEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTrackingEventResponse.ProtoReflect.Descriptor instead.
func (*SubmitTrackingEventResponse) Descriptor() ([]byte, []int) {
	return file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitTrackingEventResponse) GetSubmitStatus() int32 {
	if x != nil {
		return x.SubmitStatus
	}
	return 0
}

// message for get tracking event
type GetTrackingEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Iccid string `protobuf:"bytes,1,opt,name=iccid,proto3" json:"iccid,omitempty"`
}

func (x *GetTrackingEventRequest) Reset() {
	*x = GetTrackingEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTrackingEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackingEventRequest) ProtoMessage() {}

func (x *GetTrackingEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackingEventRequest.ProtoReflect.Descriptor instead.
func (*GetTrackingEventRequest) Descriptor() ([]byte, []int) {
	return file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_rawDescGZIP(), []int{7}
}

func (x *GetTrackingEventRequest) GetIccid() string {
	if x != nil {
		return x.Iccid
	}
	return ""
}

// message for get tracking event response
type GetTrackingEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackingEvent *TrackingEvent `protobuf:"bytes,1,opt,name=tracking_event,json=trackingEvent,proto3" json:"tracking_event,omitempty"`
}

func (x *GetTrackingEventResponse) Reset() {
	*x = GetTrackingEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTrackingEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackingEventResponse) ProtoMessage() {}

func (x *GetTrackingEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackingEventResponse.ProtoReflect.Descriptor instead.
func (*GetTrackingEventResponse) Descriptor() ([]byte, []int) {
	return file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_rawDescGZIP(), []int{8}
}

func (x *GetTrackingEventResponse) GetTrackingEvent() *TrackingEvent {
	if x != nil {
		return x.TrackingEvent
	}
	return nil
}

var File_cqlcrude_cqlcrudepb_cqlcrude_messages_proto protoreflect.FileDescriptor

var file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x63, 0x71, 0x6c, 0x63, 0x72, 0x75, 0x64, 0x65, 0x2f, 0x63, 0x71, 0x6c, 0x63, 0x72,
	0x75, 0x64, 0x65, 0x70, 0x62, 0x2f, 0x63, 0x71, 0x6c, 0x63, 0x72, 0x75, 0x64, 0x65, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63,
	0x71, 0x6c, 0x63, 0x72, 0x75, 0x64, 0x65, 0x22, 0xed, 0x03, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x63,
	0x6b, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x63, 0x63,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x63, 0x63, 0x69, 0x64, 0x12,
	0x21, 0x0a, 0x0c, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x4f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6d, 0x73, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x69, 0x6d, 0x73, 0x69, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x73, 0x69, 0x73, 0x64, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x73, 0x69, 0x73, 0x64, 0x6e, 0x12, 0x19, 0x0a,
	0x08, 0x6e, 0x65, 0x77, 0x5f, 0x69, 0x6d, 0x65, 0x69, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6e, 0x65, 0x77, 0x49, 0x6d, 0x65, 0x69, 0x12, 0x23, 0x0a, 0x0d, 0x6e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x0a,
	0x08, 0x6f, 0x6c, 0x64, 0x5f, 0x69, 0x6d, 0x65, 0x69, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6f, 0x6c, 0x64, 0x49, 0x6d, 0x65, 0x69, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d,
	0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x65, 0x6e, 0x67, 0x69,
	0x6e, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x61, 0x63, 0x5f, 0x69,
	0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x63, 0x49, 0x64, 0x12, 0x29,
	0x0a, 0x10, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e,
	0x61, 0x6c, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x74, 0x72, 0x61,
	0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0e, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x74, 0x72, 0x61, 0x63, 0x6b,
	0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x32, 0x0a, 0x1a, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x63, 0x63, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x63, 0x63, 0x69, 0x64, 0x22, 0x5e, 0x0a, 0x1b, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x63,
	0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x63, 0x63, 0x69, 0x64,
	0x12, 0x29, 0x0a, 0x10, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x5c, 0x0a, 0x1a, 0x53,
	0x75, 0x62, 0x6d, 0x69, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x0e, 0x74, 0x72, 0x61,
	0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x63, 0x71, 0x6c, 0x63, 0x72, 0x75, 0x64, 0x65, 0x2e, 0x54, 0x72, 0x61,
	0x63, 0x6b, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x1a, 0x0a, 0x18, 0x4c, 0x69, 0x73,
	0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5b, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x72, 0x61,
	0x63, 0x6b, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x71, 0x6c,
	0x63, 0x72, 0x75, 0x64, 0x65, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x22, 0x42, 0x0a, 0x1b, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x54, 0x72, 0x61, 0x63,
	0x6b, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2f, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61,
	0x63, 0x6b, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x63, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x69, 0x63, 0x63, 0x69, 0x64, 0x22, 0x5a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x71,
	0x6c, 0x63, 0x72, 0x75, 0x64, 0x65, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x42, 0x1e, 0x5a, 0x1c, 0x63, 0x71, 0x6c, 0x63, 0x72, 0x75, 0x64, 0x65, 0x2f,
	0x63, 0x71, 0x6c, 0x63, 0x72, 0x75, 0x64, 0x65, 0x70, 0x62, 0x3b, 0x63, 0x71, 0x6c, 0x63, 0x72,
	0x75, 0x64, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_rawDescOnce sync.Once
	file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_rawDescData = file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_rawDesc
)

func file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_rawDescGZIP() []byte {
	file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_rawDescOnce.Do(func() {
		file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_rawDescData)
	})
	return file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_rawDescData
}

var file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_goTypes = []interface{}{
	(*TrackingEvent)(nil),               // 0: cqlcrude.TrackingEvent
	(*DeleteTrackingEventRequest)(nil),  // 1: cqlcrude.DeleteTrackingEventRequest
	(*DeleteTrackingEventResponse)(nil), // 2: cqlcrude.DeleteTrackingEventResponse
	(*SubmitTrackingEventRequest)(nil),  // 3: cqlcrude.SubmitTrackingEventRequest
	(*ListTrackingEventRequest)(nil),    // 4: cqlcrude.ListTrackingEventRequest
	(*ListTrackingEventResponse)(nil),   // 5: cqlcrude.ListTrackingEventResponse
	(*SubmitTrackingEventResponse)(nil), // 6: cqlcrude.SubmitTrackingEventResponse
	(*GetTrackingEventRequest)(nil),     // 7: cqlcrude.GetTrackingEventRequest
	(*GetTrackingEventResponse)(nil),    // 8: cqlcrude.GetTrackingEventResponse
}
var file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_depIdxs = []int32{
	0, // 0: cqlcrude.SubmitTrackingEventRequest.tracking_event:type_name -> cqlcrude.TrackingEvent
	0, // 1: cqlcrude.ListTrackingEventResponse.tracking_event:type_name -> cqlcrude.TrackingEvent
	0, // 2: cqlcrude.GetTrackingEventResponse.tracking_event:type_name -> cqlcrude.TrackingEvent
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_init() }
func file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_init() {
	if File_cqlcrude_cqlcrudepb_cqlcrude_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackingEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTrackingEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTrackingEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitTrackingEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTrackingEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTrackingEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitTrackingEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTrackingEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTrackingEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_goTypes,
		DependencyIndexes: file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_depIdxs,
		MessageInfos:      file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_msgTypes,
	}.Build()
	File_cqlcrude_cqlcrudepb_cqlcrude_messages_proto = out.File
	file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_rawDesc = nil
	file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_goTypes = nil
	file_cqlcrude_cqlcrudepb_cqlcrude_messages_proto_depIdxs = nil
}
